Socket {
  nsp: Namespace {
    name: '/',
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Circular],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    sockets: { U77M9hqAxoIC37kGAAAB: [Socket], JfJJ7vtpxHhStGR4AAAC: [Socket] },
    connected: { U77M9hqAxoIC37kGAAAB: [Socket], JfJJ7vtpxHhStGR4AAAC: [Socket] },
    fns: [],
    ids: 0,
    rooms: [],
    flags: {},
    adapter: Adapter {
      nsp: [Circular],
      rooms: [Object],
      sids: [Object],
      encoder: Encoder {}
    },
    _events: [Object: null prototype] { connection: [Function] },
    _eventsCount: 1
  },
  server: Server {
    nsps: { '/': [Namespace] },
    parentNsps: Map {},
    _path: '/socket.io',
    _serveClient: true,
    parser: {
      protocol: 4,
      types: [Array],
      CONNECT: 0,
      DISCONNECT: 1,
      EVENT: 2,
      ACK: 3,
      ERROR: 4,
      BINARY_EVENT: 5,
      BINARY_ACK: 6,
      Encoder: [Function: Encoder],
      Decoder: [Function: Decoder]
    },
    encoder: Encoder {},
    _adapter: [Function: Adapter],
    _origins: '*:*',
    sockets: Namespace {
      name: '/',
      server: [Circular],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Adapter],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    eio: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    httpServer: Server {
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _connections: 5,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      headersTimeout: 40000,
      _connectionKey: '6::::1000',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(asyncId)]: 6
    },
    engine: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    }
  },
  adapter: Adapter {
    nsp: Namespace {
      name: '/',
      server: [Server],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Circular],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    rooms: { U77M9hqAxoIC37kGAAAB: [Room], JfJJ7vtpxHhStGR4AAAC: [Room] },
    sids: { U77M9hqAxoIC37kGAAAB: [Object], JfJJ7vtpxHhStGR4AAAC: [Object] },
    encoder: Encoder {}
  },
  id: 'EyhX7MMuyImmlsx0AAAA',
  client: Client {
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Namespace],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    conn: Socket {
      id: 'EyhX7MMuyImmlsx0AAAA',
      server: [Server],
      upgrading: false,
      upgraded: true,
      readyState: 'closed',
      writeBuffer: [],
      packetsFn: [],
      sentCallbackFn: [],
      cleanupFn: [],
      request: [IncomingMessage],
      remoteAddress: '::1',
      checkIntervalTimer: null,
      upgradeTimeoutTimer: null,
      pingTimeoutTimer: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 1500,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: null,
        [Symbol(asyncId)]: 54,
        [Symbol(triggerId)]: 39
      },
      transport: [WebSocket],
      _events: [Object: null prototype] {},
      _eventsCount: 0
    },
    encoder: Encoder {},
    decoder: Decoder { reconstructor: null, _callbacks: [Object] },
    id: 'EyhX7MMuyImmlsx0AAAA',
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=N79gVIZ',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup]
    },
    onclose: [Function: bound ],
    ondata: [Function: bound ],
    onerror: [Function: bound ],
    ondecoded: [Function: bound ],
    sockets: {},
    nsps: {},
    connectBuffer: []
  },
  conn: Socket {
    id: 'EyhX7MMuyImmlsx0AAAA',
    server: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    upgrading: false,
    upgraded: true,
    readyState: 'closed',
    writeBuffer: [],
    packetsFn: [],
    sentCallbackFn: [],
    cleanupFn: [],
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=N79gVIZ',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup]
    },
    remoteAddress: '::1',
    checkIntervalTimer: null,
    upgradeTimeoutTimer: null,
    pingTimeoutTimer: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 1500,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: null,
      [Symbol(asyncId)]: 54,
      [Symbol(triggerId)]: 39
    },
    transport: WebSocket {
      readyState: 'closed',
      discarded: false,
      socket: [WebSocket],
      writable: true,
      perMessageDeflate: [Object],
      supportsBinary: true,
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0
  },
  rooms: {},
  acks: {},
  connected: false,
  disconnected: true,
  handshake: {
    headers: {
      host: 'localhost:1000',
      connection: 'keep-alive',
      accept: '*/*',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36',
      origin: 'http://localhost:8888',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      referer: 'http://localhost:8888/admin/dashboard',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US,en;q=0.9',
      cookie: 'ci_session=5u2ehorvc2ok0mrmod93pihr3ttfmntl; io=A7qU69e5LmCopJicAAAD'
    },
    time: 'Thu Apr 30 2020 08:58:10 GMT+0300 (East Africa Time)',
    address: '::1',
    xdomain: true,
    secure: false,
    issued: 1588226290870,
    url: '/socket.io/?EIO=3&transport=polling&t=N79gVIZ',
    query: { EIO: '3', transport: 'polling', t: 'N79gVIZ' }
  },
  fns: [],
  flags: {},
  _rooms: [],
  _events: [Object: null prototype] {
    online: [Function],
    'new message': [Function],
    disconnect: [Function]
  },
  _eventsCount: 3
}
Socket {
  nsp: Namespace {
    name: '/',
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Circular],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    sockets: { U77M9hqAxoIC37kGAAAB: [Socket], JfJJ7vtpxHhStGR4AAAC: [Socket] },
    connected: { U77M9hqAxoIC37kGAAAB: [Socket], JfJJ7vtpxHhStGR4AAAC: [Socket] },
    fns: [],
    ids: 0,
    rooms: [],
    flags: {},
    adapter: Adapter {
      nsp: [Circular],
      rooms: [Object],
      sids: [Object],
      encoder: Encoder {}
    },
    _events: [Object: null prototype] { connection: [Function] },
    _eventsCount: 1
  },
  server: Server {
    nsps: { '/': [Namespace] },
    parentNsps: Map {},
    _path: '/socket.io',
    _serveClient: true,
    parser: {
      protocol: 4,
      types: [Array],
      CONNECT: 0,
      DISCONNECT: 1,
      EVENT: 2,
      ACK: 3,
      ERROR: 4,
      BINARY_EVENT: 5,
      BINARY_ACK: 6,
      Encoder: [Function: Encoder],
      Decoder: [Function: Decoder]
    },
    encoder: Encoder {},
    _adapter: [Function: Adapter],
    _origins: '*:*',
    sockets: Namespace {
      name: '/',
      server: [Circular],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Adapter],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    eio: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    httpServer: Server {
      insecureHTTPParser: undefined,
      _events: [Object: null prototype],
      _eventsCount: 5,
      _maxListeners: undefined,
      _connections: 2,
      _handle: [TCP],
      _usingWorkers: false,
      _workers: [],
      _unref: false,
      allowHalfOpen: true,
      pauseOnConnect: false,
      httpAllowHalfOpen: false,
      timeout: 120000,
      keepAliveTimeout: 5000,
      maxHeadersCount: null,
      headersTimeout: 40000,
      _connectionKey: '6::::1000',
      [Symbol(IncomingMessage)]: [Function: IncomingMessage],
      [Symbol(ServerResponse)]: [Function: ServerResponse],
      [Symbol(asyncId)]: 6
    },
    engine: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    }
  },
  adapter: Adapter {
    nsp: Namespace {
      name: '/',
      server: [Server],
      sockets: [Object],
      connected: [Object],
      fns: [],
      ids: 0,
      rooms: [],
      flags: {},
      adapter: [Circular],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    rooms: { U77M9hqAxoIC37kGAAAB: [Room], JfJJ7vtpxHhStGR4AAAC: [Room] },
    sids: { U77M9hqAxoIC37kGAAAB: [Object], JfJJ7vtpxHhStGR4AAAC: [Object] },
    encoder: Encoder {}
  },
  id: 'v7oNOiPsk9IrZ4ZaAAAD',
  client: Client {
    server: Server {
      nsps: [Object],
      parentNsps: Map {},
      _path: '/socket.io',
      _serveClient: true,
      parser: [Object],
      encoder: Encoder {},
      _adapter: [Function: Adapter],
      _origins: '*:*',
      sockets: [Namespace],
      eio: [Server],
      httpServer: [Server],
      engine: [Server]
    },
    conn: Socket {
      id: 'v7oNOiPsk9IrZ4ZaAAAD',
      server: [Server],
      upgrading: false,
      upgraded: true,
      readyState: 'closed',
      writeBuffer: [],
      packetsFn: [],
      sentCallbackFn: [],
      cleanupFn: [],
      request: [IncomingMessage],
      remoteAddress: '::1',
      checkIntervalTimer: null,
      upgradeTimeoutTimer: null,
      pingTimeoutTimer: Timeout {
        _idleTimeout: -1,
        _idlePrev: null,
        _idleNext: null,
        _idleStart: 31621,
        _onTimeout: null,
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: true,
        [Symbol(refed)]: null,
        [Symbol(asyncId)]: 227,
        [Symbol(triggerId)]: 177
      },
      transport: [WebSocket],
      _events: [Object: null prototype] {},
      _eventsCount: 0
    },
    encoder: Encoder {},
    decoder: Decoder { reconstructor: null, _callbacks: [Object] },
    id: 'v7oNOiPsk9IrZ4ZaAAAD',
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=N79gWFn',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup]
    },
    onclose: [Function: bound ],
    ondata: [Function: bound ],
    onerror: [Function: bound ],
    ondecoded: [Function: bound ],
    sockets: {},
    nsps: {},
    connectBuffer: []
  },
  conn: Socket {
    id: 'v7oNOiPsk9IrZ4ZaAAAD',
    server: Server {
      clients: [Object],
      clientsCount: 2,
      wsEngine: 'ws',
      pingTimeout: 5000,
      pingInterval: 25000,
      upgradeTimeout: 10000,
      maxHttpBufferSize: 100000000,
      transports: [Array],
      allowUpgrades: true,
      allowRequest: [Function: bound ],
      cookie: 'io',
      cookiePath: '/',
      cookieHttpOnly: true,
      perMessageDeflate: [Object],
      httpCompression: [Object],
      initialPacket: [Array],
      ws: [WebSocketServer],
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    upgrading: false,
    upgraded: true,
    readyState: 'closed',
    writeBuffer: [],
    packetsFn: [],
    sentCallbackFn: [],
    cleanupFn: [],
    request: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 1,
      _maxListeners: undefined,
      socket: [Socket],
      connection: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '/socket.io/?EIO=3&transport=polling&t=N79gWFn',
      method: 'GET',
      statusCode: null,
      statusMessage: null,
      client: [Socket],
      _consuming: false,
      _dumped: true,
      _query: [Object: null prototype],
      res: [ServerResponse],
      cleanup: [Function: cleanup]
    },
    remoteAddress: '::1',
    checkIntervalTimer: null,
    upgradeTimeoutTimer: null,
    pingTimeoutTimer: Timeout {
      _idleTimeout: -1,
      _idlePrev: null,
      _idleNext: null,
      _idleStart: 31621,
      _onTimeout: null,
      _timerArgs: undefined,
      _repeat: null,
      _destroyed: true,
      [Symbol(refed)]: null,
      [Symbol(asyncId)]: 227,
      [Symbol(triggerId)]: 177
    },
    transport: WebSocket {
      readyState: 'closed',
      discarded: false,
      socket: [WebSocket],
      writable: true,
      perMessageDeflate: [Object],
      supportsBinary: true,
      _events: [Object: null prototype],
      _eventsCount: 1
    },
    _events: [Object: null prototype] {},
    _eventsCount: 0
  },
  rooms: {},
  acks: {},
  connected: false,
  disconnected: true,
  handshake: {
    headers: {
      host: 'localhost:1000',
      connection: 'keep-alive',
      accept: '*/*',
      'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36',
      origin: 'http://localhost:8888',
      'sec-fetch-site': 'same-site',
      'sec-fetch-mode': 'cors',
      'sec-fetch-dest': 'empty',
      referer: 'http://localhost:8888/admin/dashboard',
      'accept-encoding': 'gzip, deflate, br',
      'accept-language': 'en-US,en;q=0.9',
      cookie: 'ci_session=5u2ehorvc2ok0mrmod93pihr3ttfmntl; io=EyhX7MMuyImmlsx0AAAA'
    },
    time: 'Thu Apr 30 2020 08:58:14 GMT+0300 (East Africa Time)',
    address: '::1',
    xdomain: true,
    secure: false,
    issued: 1588226294775,
    url: '/socket.io/?EIO=3&transport=polling&t=N79gWFn',
    query: { EIO: '3', transport: 'polling', t: 'N79gWFn' }
  },
  fns: [],
  flags: {},
  _rooms: [],
  _events: [Object: null prototype] {
    online: [Function],
    'new message': [Function],
    disconnect: [Function]
  },
  _eventsCount: 3
}
